apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: kong
data:
  kong.yaml: |
    _format_version: "2.1"
    _transform: true

    services:
      - name: sentence-analyzer
        url: http://sentence-analyzer-service.default.svc.cluster.local:8080
        routes:
          - name: sentence-analyzer-route
            paths:
              - /analyze
            strip_path: false
        plugins:
          - name: oidc
            config:
              client_id: ${OIDC_CLIENT_ID}
              client_secret: ${OIDC_CLIENT_SECRET}
              discovery: ${OIDC_DISCOVERY_URL}
              bearer_only: "yes"
              realm: "sentence-analyzer"
              ssl_verify: "no"
              token_endpoint_auth_method: client_secret_post
              # Introspection endpoint is only needed for certain OIDC providers
              # Auth0 and other providers that use JWT validation don't require it
              # If using Auth0, you can leave this empty or remove it
              introspection_endpoint: ${OIDC_INTROSPECTION_URL}