apiVersion: v1
kind: Service
metadata:
  name: sentence-analyzer
  namespace: sentence-analyzer
  labels:
    app: sentence-analyzer
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: sentence-analyzer